<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220406130027 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cart_item DROP CONSTRAINT cart_item_session_id_fkey');
        $this->addSql('ALTER TABLE cart_item DROP CONSTRAINT cart_item_product_id_fkey');
        $this->addSql('DROP INDEX idx_cart_item_session_id');
        $this->addSql('DROP INDEX IDX_F0FE25274584665A');
        $this->addSql('ALTER TABLE cart_item ADD product_id_id INT NOT NULL');
        $this->addSql('ALTER TABLE cart_item ADD shopping_session_id_id INT NOT NULL');
        $this->addSql('ALTER TABLE cart_item DROP session_id');
        $this->addSql('ALTER TABLE cart_item DROP product_id');
        $this->addSql('ALTER TABLE cart_item ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE cart_item ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cart_item ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE cart_item ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE cart_item ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cart_item ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE cart_item ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cart_item ALTER deactivated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN cart_item.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cart_item.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cart_item.deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE cart_item ADD CONSTRAINT FK_F0FE2527DE18E50B FOREIGN KEY (product_id_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cart_item ADD CONSTRAINT FK_F0FE2527D6ECCE96 FOREIGN KEY (shopping_session_id_id) REFERENCES shopping_session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_F0FE2527DE18E50B ON cart_item (product_id_id)');
        $this->addSql('CREATE INDEX IDX_F0FE2527D6ECCE96 ON cart_item (shopping_session_id_id)');
        $this->addSql('ALTER TABLE company DROP CONSTRAINT company_category_id_fkey');
        $this->addSql('DROP INDEX idx_company_category_id');
        $this->addSql('ALTER TABLE company ADD category_id_id INT NOT NULL');
        $this->addSql('ALTER TABLE company DROP category_id');
        $this->addSql('ALTER TABLE company DROP country_code');
        $this->addSql('ALTER TABLE company ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE company ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE company ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company ALTER deactivated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN company.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN company.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN company.deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F9777D11E FOREIGN KEY (category_id_id) REFERENCES company_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_4FBF094F9777D11E ON company (category_id_id)');
        $this->addSql('ALTER INDEX idx_company_owner_id RENAME TO IDX_4FBF094F7E3C61F9');
        $this->addSql('ALTER TABLE company_address DROP CONSTRAINT company_address_company_id_fkey');
        $this->addSql('DROP INDEX idx_company_address_company_id');
        $this->addSql('ALTER TABLE company_address ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE company_address ALTER postal_code TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE company_address ALTER country TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE company_address ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_address ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company_address ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE company_address ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_address ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company_address ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_address ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company_address RENAME COLUMN company_id TO company_id_id');
        $this->addSql('COMMENT ON COLUMN company_address.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN company_address.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN company_address.deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE company_address ADD CONSTRAINT FK_2D1C755638B53C32 FOREIGN KEY (company_id_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_2D1C755638B53C32 ON company_address (company_id_id)');
        $this->addSql('DROP INDEX idx_company_category_title');
        $this->addSql('ALTER TABLE company_category ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE company_category ALTER title TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE company_category ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_category ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company_category ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE company_category ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_category ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company_category ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_category ALTER deactivated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN company_category.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN company_category.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN company_category.deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE credit DROP CONSTRAINT credit_user_id_fkey');
        $this->addSql('DROP INDEX idx_credit_user_id');
        $this->addSql('DROP INDEX credit_reference_key');
        $this->addSql('ALTER TABLE credit ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE credit ALTER reference TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE credit ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE credit ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE credit ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE credit ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE credit ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE credit ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE credit ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE credit RENAME COLUMN user_id TO user_id_id');
        $this->addSql('ALTER TABLE credit RENAME COLUMN expiry TO expiry_date');
        $this->addSql('COMMENT ON COLUMN credit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN credit.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN credit.deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFE9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_1CC16EFE9D86650F ON credit (user_id_id)');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT order_user_id_fkey');
        $this->addSql('DROP INDEX order_reference_key');
        $this->addSql('DROP INDEX idx_order_reference');
        $this->addSql('DROP INDEX idx_order_user_id');
        $this->addSql('ALTER TABLE "order" DROP amount');
        $this->addSql('ALTER TABLE "order" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "order" ALTER reference TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE "order" ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE "order" ALTER status TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE "order" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "order" ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE "order" ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE "order" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "order" ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE "order" ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "order" ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE "order" RENAME COLUMN user_id TO user_id_id');
        $this->addSql('COMMENT ON COLUMN "order".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "order".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "order".deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F52993989D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_F52993989D86650F ON "order" (user_id_id)');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT order_item_order_id_fkey');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT order_item_product_id_fkey');
        $this->addSql('DROP INDEX idx_order_item_product_id');
        $this->addSql('DROP INDEX idx_order_item_order_id');
        $this->addSql('ALTER TABLE order_item ADD order_id_id INT NOT NULL');
        $this->addSql('ALTER TABLE order_item ADD product_id_id INT NOT NULL');
        $this->addSql('ALTER TABLE order_item DROP order_id');
        $this->addSql('ALTER TABLE order_item DROP product_id');
        $this->addSql('ALTER TABLE order_item ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE order_item ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE order_item ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE order_item ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE order_item ALTER deactivated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN order_item.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN order_item.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN order_item.deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F09FCDAEAAA FOREIGN KEY (order_id_id) REFERENCES "order" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F09DE18E50B FOREIGN KEY (product_id_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_52EA1F09FCDAEAAA ON order_item (order_id_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F09DE18E50B ON order_item (product_id_id)');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT product_category_id_fkey');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT product_company_id_fkey');
        $this->addSql('DROP INDEX idx_product_company_id');
        $this->addSql('DROP INDEX IDX_D34A04AD12469DE2');
        $this->addSql('ALTER TABLE product ADD product_category_id_id INT NOT NULL');
        $this->addSql('ALTER TABLE product ADD company_id_id INT NOT NULL');
        $this->addSql('ALTER TABLE product DROP category_id');
        $this->addSql('ALTER TABLE product DROP company_id');
        $this->addSql('ALTER TABLE product ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER description TYPE TEXT');
        $this->addSql('ALTER TABLE product ALTER description DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE product ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE product RENAME COLUMN disponibility TO available');
        $this->addSql('COMMENT ON COLUMN product.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN product.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN product.deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADC41EAF32 FOREIGN KEY (product_category_id_id) REFERENCES product_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD38B53C32 FOREIGN KEY (company_id_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_D34A04ADC41EAF32 ON product (product_category_id_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD38B53C32 ON product (company_id_id)');
        $this->addSql('ALTER TABLE product_category ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE product_category ALTER name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE product_category ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product_category ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE product_category ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE product_category ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product_category ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE product_category ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product_category ALTER deactivated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN product_category.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN product_category.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN product_category.deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE shopping_session DROP CONSTRAINT shopping_session_user_id_fkey');
        $this->addSql('DROP INDEX idx_shopping_session_user_id');
        $this->addSql('ALTER TABLE shopping_session ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE shopping_session ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE shopping_session ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE shopping_session ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE shopping_session ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE shopping_session ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE shopping_session ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE shopping_session ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE shopping_session RENAME COLUMN user_id TO user_id_id');
        $this->addSql('COMMENT ON COLUMN shopping_session.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN shopping_session.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN shopping_session.deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE shopping_session ADD CONSTRAINT FK_CECE98A69D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_CECE98A69D86650F ON shopping_session (user_id_id)');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT user_last_address_fkey');
        $this->addSql('DROP INDEX IDX_8D93D6496BC253C9');
        $this->addSql('ALTER TABLE "user" DROP last_address');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER first_name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE "user" ALTER last_name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE "user" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER deactivated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE user_address DROP CONSTRAINT user_address_user_id_fkey');
        $this->addSql('DROP INDEX idx_user_address_user_id');
        $this->addSql('ALTER TABLE user_address ADD phone_number VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE user_address ADD selected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE user_address DROP mobile');
        $this->addSql('ALTER TABLE user_address ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE user_address ALTER name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE user_address ALTER postal_code TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE user_address ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE user_address ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE user_address ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE user_address ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE user_address ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE user_address ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE user_address ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE user_address RENAME COLUMN user_id TO user_id_id');
        $this->addSql('COMMENT ON COLUMN user_address.selected_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_address.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_address.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_address.deactivated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE user_address ADD CONSTRAINT FK_5543718B9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_5543718B9D86650F ON user_address (user_id_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F52993989D86650F');
        $this->addSql('DROP INDEX IDX_F52993989D86650F');
        $this->addSql('ALTER TABLE "order" ADD amount INT NOT NULL');
        $this->addSql('CREATE SEQUENCE order_id_seq');
        $this->addSql('SELECT setval(\'order_id_seq\', (SELECT MAX(id) FROM "order"))');
        $this->addSql('ALTER TABLE "order" ALTER id SET DEFAULT nextval(\'order_id_seq\')');
        $this->addSql('ALTER TABLE "order" ALTER reference TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE "order" ALTER status SET DEFAULT \'Waiting payment\'');
        $this->addSql('ALTER TABLE "order" ALTER status TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE "order" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "order" ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE "order" ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE "order" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "order" ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE "order" ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "order" ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE "order" RENAME COLUMN user_id_id TO user_id');
        $this->addSql('COMMENT ON COLUMN "order".created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN "order".updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN "order".deactivated_at IS NULL');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT order_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX order_reference_key ON "order" (reference)');
        $this->addSql('CREATE INDEX idx_order_reference ON "order" (reference)');
        $this->addSql('CREATE INDEX idx_order_user_id ON "order" (user_id)');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F09FCDAEAAA');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F09DE18E50B');
        $this->addSql('DROP INDEX IDX_52EA1F09FCDAEAAA');
        $this->addSql('DROP INDEX IDX_52EA1F09DE18E50B');
        $this->addSql('ALTER TABLE order_item ADD order_id INT NOT NULL');
        $this->addSql('ALTER TABLE order_item ADD product_id INT NOT NULL');
        $this->addSql('ALTER TABLE order_item DROP order_id_id');
        $this->addSql('ALTER TABLE order_item DROP product_id_id');
        $this->addSql('CREATE SEQUENCE order_item_id_seq');
        $this->addSql('SELECT setval(\'order_item_id_seq\', (SELECT MAX(id) FROM order_item))');
        $this->addSql('ALTER TABLE order_item ALTER id SET DEFAULT nextval(\'order_item_id_seq\')');
        $this->addSql('ALTER TABLE order_item ALTER quantity SET DEFAULT 1');
        $this->addSql('ALTER TABLE order_item ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE order_item ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE order_item ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE order_item ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE order_item ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE order_item ALTER deactivated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN order_item.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN order_item.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN order_item.deactivated_at IS NULL');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT order_item_order_id_fkey FOREIGN KEY (order_id) REFERENCES "order" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT order_item_product_id_fkey FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_order_item_product_id ON order_item (product_id)');
        $this->addSql('CREATE INDEX idx_order_item_order_id ON order_item (order_id)');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04ADC41EAF32');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD38B53C32');
        $this->addSql('DROP INDEX IDX_D34A04ADC41EAF32');
        $this->addSql('DROP INDEX IDX_D34A04AD38B53C32');
        $this->addSql('ALTER TABLE product ADD category_id INT NOT NULL');
        $this->addSql('ALTER TABLE product ADD company_id INT NOT NULL');
        $this->addSql('ALTER TABLE product DROP product_category_id_id');
        $this->addSql('ALTER TABLE product DROP company_id_id');
        $this->addSql('CREATE SEQUENCE product_id_seq');
        $this->addSql('SELECT setval(\'product_id_seq\', (SELECT MAX(id) FROM product))');
        $this->addSql('ALTER TABLE product ALTER id SET DEFAULT nextval(\'product_id_seq\')');
        $this->addSql('ALTER TABLE product ALTER description TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE product ALTER description DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE product ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE product ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE product RENAME COLUMN available TO disponibility');
        $this->addSql('COMMENT ON COLUMN product.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN product.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN product.deactivated_at IS NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_category_id_fkey FOREIGN KEY (category_id) REFERENCES product_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_company_id_fkey FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_product_company_id ON product (company_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
        $this->addSql('CREATE SEQUENCE product_category_id_seq');
        $this->addSql('SELECT setval(\'product_category_id_seq\', (SELECT MAX(id) FROM product_category))');
        $this->addSql('ALTER TABLE product_category ALTER id SET DEFAULT nextval(\'product_category_id_seq\')');
        $this->addSql('ALTER TABLE product_category ALTER name TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE product_category ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product_category ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE product_category ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE product_category ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product_category ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE product_category ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE product_category ALTER deactivated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN product_category.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN product_category.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN product_category.deactivated_at IS NULL');
        $this->addSql('CREATE SEQUENCE company_category_id_seq');
        $this->addSql('SELECT setval(\'company_category_id_seq\', (SELECT MAX(id) FROM company_category))');
        $this->addSql('ALTER TABLE company_category ALTER id SET DEFAULT nextval(\'company_category_id_seq\')');
        $this->addSql('ALTER TABLE company_category ALTER title TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE company_category ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_category ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE company_category ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE company_category ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_category ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company_category ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_category ALTER deactivated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN company_category.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN company_category.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN company_category.deactivated_at IS NULL');
        $this->addSql('CREATE INDEX idx_company_category_title ON company_category (title)');
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094F9777D11E');
        $this->addSql('DROP INDEX IDX_4FBF094F9777D11E');
        $this->addSql('ALTER TABLE company ADD country_code INT NOT NULL');
        $this->addSql('CREATE SEQUENCE company_id_seq');
        $this->addSql('SELECT setval(\'company_id_seq\', (SELECT MAX(id) FROM company))');
        $this->addSql('ALTER TABLE company ALTER id SET DEFAULT nextval(\'company_id_seq\')');
        $this->addSql('ALTER TABLE company ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE company ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE company ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company RENAME COLUMN category_id_id TO category_id');
        $this->addSql('COMMENT ON COLUMN company.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN company.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN company.deactivated_at IS NULL');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT company_category_id_fkey FOREIGN KEY (category_id) REFERENCES company_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_company_category_id ON company (category_id)');
        $this->addSql('ALTER INDEX idx_4fbf094f7e3c61f9 RENAME TO idx_company_owner_id');
        $this->addSql('ALTER TABLE "user" ADD last_address INT NOT NULL');
        $this->addSql('CREATE SEQUENCE user_id_seq');
        $this->addSql('SELECT setval(\'user_id_seq\', (SELECT MAX(id) FROM "user"))');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\')');
        $this->addSql('ALTER TABLE "user" ALTER first_name TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE "user" ALTER last_name TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE "user" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE "user" ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER deactivated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN "user".deactivated_at IS NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT user_last_address_fkey FOREIGN KEY (last_address) REFERENCES user_address (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_8D93D6496BC253C9 ON "user" (last_address)');
        $this->addSql('ALTER TABLE company_address DROP CONSTRAINT FK_2D1C755638B53C32');
        $this->addSql('DROP INDEX IDX_2D1C755638B53C32');
        $this->addSql('CREATE SEQUENCE company_address_id_seq');
        $this->addSql('SELECT setval(\'company_address_id_seq\', (SELECT MAX(id) FROM company_address))');
        $this->addSql('ALTER TABLE company_address ALTER id SET DEFAULT nextval(\'company_address_id_seq\')');
        $this->addSql('ALTER TABLE company_address ALTER postal_code TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE company_address ALTER country TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE company_address ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_address ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE company_address ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE company_address ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_address ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company_address ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE company_address ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE company_address RENAME COLUMN company_id_id TO company_id');
        $this->addSql('COMMENT ON COLUMN company_address.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN company_address.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN company_address.deactivated_at IS NULL');
        $this->addSql('ALTER TABLE company_address ADD CONSTRAINT company_address_company_id_fkey FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_company_address_company_id ON company_address (company_id)');
        $this->addSql('ALTER TABLE user_address DROP CONSTRAINT FK_5543718B9D86650F');
        $this->addSql('DROP INDEX IDX_5543718B9D86650F');
        $this->addSql('ALTER TABLE user_address ADD mobile VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE user_address DROP phone_number');
        $this->addSql('ALTER TABLE user_address DROP selected_at');
        $this->addSql('CREATE SEQUENCE user_address_id_seq');
        $this->addSql('SELECT setval(\'user_address_id_seq\', (SELECT MAX(id) FROM user_address))');
        $this->addSql('ALTER TABLE user_address ALTER id SET DEFAULT nextval(\'user_address_id_seq\')');
        $this->addSql('ALTER TABLE user_address ALTER name TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE user_address ALTER postal_code TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE user_address ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE user_address ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE user_address ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE user_address ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE user_address ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE user_address ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE user_address ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE user_address RENAME COLUMN user_id_id TO user_id');
        $this->addSql('COMMENT ON COLUMN user_address.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN user_address.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN user_address.deactivated_at IS NULL');
        $this->addSql('ALTER TABLE user_address ADD CONSTRAINT user_address_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_user_address_user_id ON user_address (user_id)');
        $this->addSql('ALTER TABLE shopping_session DROP CONSTRAINT FK_CECE98A69D86650F');
        $this->addSql('DROP INDEX IDX_CECE98A69D86650F');
        $this->addSql('CREATE SEQUENCE shopping_session_id_seq');
        $this->addSql('SELECT setval(\'shopping_session_id_seq\', (SELECT MAX(id) FROM shopping_session))');
        $this->addSql('ALTER TABLE shopping_session ALTER id SET DEFAULT nextval(\'shopping_session_id_seq\')');
        $this->addSql('ALTER TABLE shopping_session ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE shopping_session ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE shopping_session ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE shopping_session ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE shopping_session ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE shopping_session ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE shopping_session ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE shopping_session RENAME COLUMN user_id_id TO user_id');
        $this->addSql('COMMENT ON COLUMN shopping_session.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN shopping_session.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN shopping_session.deactivated_at IS NULL');
        $this->addSql('ALTER TABLE shopping_session ADD CONSTRAINT shopping_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX idx_shopping_session_user_id ON shopping_session (user_id)');
        $this->addSql('ALTER TABLE cart_item DROP CONSTRAINT FK_F0FE2527DE18E50B');
        $this->addSql('ALTER TABLE cart_item DROP CONSTRAINT FK_F0FE2527D6ECCE96');
        $this->addSql('DROP INDEX IDX_F0FE2527DE18E50B');
        $this->addSql('DROP INDEX IDX_F0FE2527D6ECCE96');
        $this->addSql('ALTER TABLE cart_item ADD session_id INT NOT NULL');
        $this->addSql('ALTER TABLE cart_item ADD product_id INT NOT NULL');
        $this->addSql('ALTER TABLE cart_item DROP product_id_id');
        $this->addSql('ALTER TABLE cart_item DROP shopping_session_id_id');
        $this->addSql('CREATE SEQUENCE cart_item_id_seq');
        $this->addSql('SELECT setval(\'cart_item_id_seq\', (SELECT MAX(id) FROM cart_item))');
        $this->addSql('ALTER TABLE cart_item ALTER id SET DEFAULT nextval(\'cart_item_id_seq\')');
        $this->addSql('ALTER TABLE cart_item ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cart_item ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE cart_item ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE cart_item ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cart_item ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE cart_item ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE cart_item ALTER deactivated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN cart_item.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN cart_item.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN cart_item.deactivated_at IS NULL');
        $this->addSql('ALTER TABLE cart_item ADD CONSTRAINT cart_item_session_id_fkey FOREIGN KEY (session_id) REFERENCES shopping_session (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cart_item ADD CONSTRAINT cart_item_product_id_fkey FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_cart_item_session_id ON cart_item (session_id)');
        $this->addSql('CREATE INDEX IDX_F0FE25274584665A ON cart_item (product_id)');
        $this->addSql('ALTER TABLE credit DROP CONSTRAINT FK_1CC16EFE9D86650F');
        $this->addSql('DROP INDEX IDX_1CC16EFE9D86650F');
        $this->addSql('CREATE SEQUENCE credit_id_seq');
        $this->addSql('SELECT setval(\'credit_id_seq\', (SELECT MAX(id) FROM credit))');
        $this->addSql('ALTER TABLE credit ALTER id SET DEFAULT nextval(\'credit_id_seq\')');
        $this->addSql('ALTER TABLE credit ALTER reference TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE credit ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE credit ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE credit ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE credit ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE credit ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE credit ALTER deactivated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE credit ALTER deactivated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE credit RENAME COLUMN user_id_id TO user_id');
        $this->addSql('ALTER TABLE credit RENAME COLUMN expiry_date TO expiry');
        $this->addSql('COMMENT ON COLUMN credit.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN credit.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN credit.deactivated_at IS NULL');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT credit_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_credit_user_id ON credit (user_id)');
        $this->addSql('CREATE UNIQUE INDEX credit_reference_key ON credit (reference)');
    }
}
